### ISSUE TITLE
Cholmod error 'invalid xtype'

### ISSUE THREAD

**Issue by factoryofthesun** [geometryprocessing/algebraic-contours#1]
Thanks for this project. I've built the project (turning off -werror) and attempted to run it on the [spot model ](https://www.cs.cmu.edu/~kmcrane/Projects/ModelRepository/spot.zip) but receive the following error. 
> CHOLMOD error: invalid xtype. file: /net/projects/ranalab/guanzhi/algebraic-contours/build/_deps/suitesparse-src/CHOLMOD/Cholesky/cholmod_analyze.c line: 431
CHOLMOD error: argument missing. file: /net/projects/ranalab/guanzhi/algebraic-contours/build/_deps/suitesparse-src/CHOLMOD/Cholesky/cholmod_factorize.c line: 121
Segmentation fault

My system details are below

> NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Any idea what could be the issue?

**Comment by rjc8237** [comment]
Hello Richard,

Thank you for alerting me to the -werror issue! I pushed some changes
fixing the warnings/errors, so it should build properly now without turning
off -werror.

This issue isn't familiar to me, and it currently builds without issue on
my Ubuntu 22.04 machine. I can try to ask a few coworkers to build it to
see if they run into the same bug, but otherwise I'm not sure what is
causing the compatibility issue.

Best,
Ryan Capouellez

**Comment by factoryofthesun** [comment]
Hi Ryan, 

Thanks for the -werror fix! Is there an update with having your coworkers test the build? 

Thanks,
Richard

**Comment by rjc8237** [comment]
Hello,

I had one of my labmates build it, and they didn't run into any issues.

CHOLMOD is part of an external library that I'm fetching with CMake; you
could try building it directly from the following repo:
        GITHUB_REPOSITORY sergiud/SuiteSparse
        GIT_TAG 0ba07264225518a487a0a9a8e675f6e36c96a68a
The cmake file has a lot of additional compiler options and settings for
CHOLMOD, but this might indicate if there is some compatibility issue with
the basic CHOLMOD installation.

Best,
Ryan Capouellez

**Comment by factoryofthesun** [comment]
Hi Ryan, 

It turns out that the program just didn't seem to like the mesh I was using! I was trying to use Keenan's spot mesh from his [website](https://www.cs.cmu.edu/~kmcrane/Projects/ModelRepository/spot.zip) but the resulting CHOLMOD matrix was throwing the invalid xtype error. My guess is this is because the spot model has disconnected UV components rather than cone vertices. I was able to successfully run the program using the meshes from your website. Thanks for the help!

Best,
Richard
